# Generated by Django 2.2.1 on 2020-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Imagem do projeto'),
        ),
    ]
