# Generated by Django 3.0.4 on 2020-03-28 02:54

import apps.companies.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='New companies', max_length=128, verbose_name='Nome da companhia')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.companies.models.company_directory_path, verbose_name='Imagem da companhia')),
            ],
            options={
                'verbose_name': 'Companhia',
                'verbose_name_plural': 'Companhias',
            },
        ),
    ]
