# Generated by Django 3.0.4 on 2020-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200328_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Nova companhia', max_length=128, verbose_name='Nome da companhia'),
        ),
    ]
