# Generated by Django 3.0.4 on 2020-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_projects',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Projetos favoritos'),
        ),
    ]
