# Generated by Django 3.0.4 on 2020-05-17 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=64, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default=('Média', 'Média'), max_length=128, verbose_name='Prioridade')),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tempo estimado')),
                ('work_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tempo trabalhado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
