# Generated by Django 3.0.4 on 2020-03-28 03:16

import apps.teams.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(default='New team', max_length=128, verbose_name='Nome do time')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.teams.models.team_directory_path, verbose_name='Imagem do time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_company', to='companies.Company')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
    ]
